# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prize',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
